---
- hosts: cisco-ios
  gather_facts: no
  connection: local
 
  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: vault-vars.yml
 
  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ ROOT_USER }}"
        password: "{{ ROOT_PASSWORD }}"
 
  - name: WRITE MEMORY
    ios_command:
      provider: "{{ provider }}"
      commands:
        - wr mem 
    register: write
 
  - debug: var=write.stdout_lines
