---
- name: Test junos_get_facts module
  hosts: juniper
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:

    - name: TEST 1 - Gather Facts
      junos_get_facts:
        host: "{{ inventory_host }}"
        user: guest
        passwd: password
      ignore_errors: True
      register: test1

  #  - debug: var=test1

    - name: Check TEST 1
      assert:
        that:
          - test1.facts.hostname
          - test1.facts.serialnumber
          - test1.facts.model
          - test1.facts.fqdn
